### ISSUE TITLE
Bardenay Happy Hour, March 24, 6PM

### ISSUE THREAD

**Issue by joshjens** [beerjs/boise#3]
http://www.meetup.com/BeerJSBoise/events/220971850/

**Comment by junosuarez** [comment]
ooh, I might be able to make this!

**Comment by joshjens** [comment]
:thumbsup:

**Comment by joshjens** [comment]
![img_1003](https://cloud.githubusercontent.com/assets/8519287/6642199/7e05749a-c968-11e4-8522-fb700e00e919.JPG)

**Comment by jmcdannel** [comment]
[image: Inline image 1]
[image: Inline image 2]

On Fri, Mar 13, 2015 at 10:05 AM, Joshua Jensen notifications@github.com
wrote:

> [image: img_1003]
> https://cloud.githubusercontent.com/assets/8519287/6642192/72ed3886-c968-11e4-9fe0-11cd7967c825.JPG
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beerjs/boise/issues/3#issuecomment-79081785.

## 

Josh McDannel

_drops mic_

**Comment by joshjens** [comment]
Tomorrow Night!
